#!/usr/bin/python
from kzpy3.utils3 import *

Data = {}
items = ['day','month','year','hour','minutes','seconds']
for d in items:
	q = input(d+"> ")
	assert type(q) == int
	assert q >= 0
	Data[d] = q
	
	if q > 9:
		Data[d+'/string'] = str(q)
	else:
		Data[d+'/string'] = '0'+str(q)
D = {}

assert Data['day'] <= 31
assert Data['month'] <= 12
assert Data['year'] <= 2050
assert Data['year'] >= 2018
assert Data['minutes'] <= 59
assert Data['seconds'] <= 59

MMDDhhmmyyyy_ss = Data['month/string'] + \
	Data['day/string'] + \
	Data['hour/string'] + \
	Data['minutes/string'] + \
	Data['year/string'] + \
	"." +\
	Data['seconds/string']

cg("new_date_time_string:",MMDDhhmmyyyy_ss)

os.system(d2s("sudo date",MMDDhhmmyyyy_ss))
#os.system("date")