# file generated by kzpy3/drafts/subscribe.py Monday, 15 Jul 2019, 09:01:56 PM
from kzpy3.utils3 import *
import rospy
from std_msgs.msg import Int32,Float32
from geometry_msgs.msg import Vector3
from std_msgs.msg import Int32MultiArray,Float32MultiArray
from sensor_msgs.msg import Image
import cv_bridge
bridge = cv_bridge.CvBridge()

S = {}

S['right_image'] = 0
def right_image__callback(data):
    S['right_image'] = bridge.imgmsg_to_cv2(data,'rgb8')
rospy.Subscriber(
    '/bair_car/zed/right/image_rect_color',
    Image,
    callback=right_image__callback,
    queue_size=1
)

            
S['acc_x'] = 0
S['acc_y'] = 0
S['acc_z'] = 0
def acc__callback(data):
    S['acc_x'] = data.x
    S['acc_y'] = data.y
    S['acc_z'] = data.z
rospy.Subscriber(
    '/bair_car/acc',
    Vector3,
    callback=acc__callback,
    queue_size=3
)

        
S['steer'] = 49
def steer__callback(data):
    S['steer'] = data.data
rospy.Subscriber(
    '/bair_car/steer',
    Int32,
    callback=steer__callback,
    queue_size=5
)

            
