##############################################################
########################    SUBSCRIBE  #######################
###
from kzpy3.vis3 import *
imports = """# file generated by """+__file__+" "+time_str('Pretty')+"""
from kzpy3.utils3 import *
import rospy
from std_msgs.msg import Int32,Float32
from geometry_msgs.msg import Vector3
from std_msgs.msg import Int32MultiArray,Float32MultiArray
from sensor_msgs.msg import Image
import cv_bridge
bridge = cv_bridge.CvBridge()

"""

#,a
bcs = '/bair_car/'
Topics = {
    'motor': {
        'topic': bcs+'motor',
        'type': 'Int32',
        'init_val': 49,
        'qs': 5,
    },
    'steer': {
        'topic': bcs+'steer',
        'type': 'Int32',
        'init_val': 49,
        'qs': 5,
    },
    'acc': {
        'topic': bcs+'acc',
        'type': 'Vector3',
        'init_val': 0,
        'qs': 3,  
    },
    'left_image': {
        'topic': bcs+"zed/left/image_rect_color",
        'type': 'Image',
        'init_val': 0,
        'qs': 1,
    },
    'right_image': {
        'topic': bcs+"zed/right/image_rect_color",
        'type': 'Image',
        'init_val': 0,
        'qs': 1,
    },
}


topics_to_use = ['right_image','acc','steer']


def get_ros_strings(topics_to_use,Topics):
    s = imports
    s = s+"S = {}\n"
    for k in topics_to_use:
        if Topics[k]['type'] in ['Int32','Float32']:
            s = s + """
S['NAME'] = INIT_VAL
def NAME__callback(data):
    S['NAME'] = data.data
rospy.Subscriber(
    'TOPIC',
    TYPE,
    callback=NAME__callback,
    queue_size=QS
)

            """
        elif Topics[k]['type'] in ['Vector3']:
            s = s + """
S['NAME_x'] = INIT_VAL
S['NAME_y'] = INIT_VAL
S['NAME_z'] = INIT_VAL
def NAME__callback(data):
    S['NAME_x'] = data.x
    S['NAME_y'] = data.y
    S['NAME_z'] = data.z
rospy.Subscriber(
    'TOPIC',
    TYPE,
    callback=NAME__callback,
    queue_size=QS
)

        """
        elif Topics[k]['type'] in ['Image']:
            s = s + """
S['NAME'] = INIT_VAL
def NAME__callback(data):
    S['NAME'] = bridge.imgmsg_to_cv2(data,'rgb8')
rospy.Subscriber(
    'TOPIC',
    TYPE,
    callback=NAME__callback,
    queue_size=QS
)

            """
        s = s.replace('NAME',k)
        s = s.replace('INIT_VAL',str(Topics[k]['init_val']))
        s = s.replace('TOPIC',Topics[k]['topic'])
        s = s.replace('TYPE',Topics[k]['type'])
        s = s.replace('QS',str(Topics[k]['qs']))
    return s

s = get_ros_strings(topics_to_use,Topics)
print s
text_to_file(opjk('topics.py'),s)
#,b


#EOF
