#!/usr/bin/env python

from kzpy3.utils3 import *

try:
	bagpath = Arguments['path']
except:
	bagpath = opjk("scripts/__local__/bagpath")

os.system("roscore")

timer = Timer(60*30)

while not timer.check():
	os.system("rosbag play "+bagpath+"/*.bag")

cg("\nbagloop complete.\n")

#EOF
