#!/usr/bin/env python

from kzpy3.utils3 import *

try:
	bagpath = Arguments['path']
except:
	bagpath = opjk("scripts/__local__/bagpath")

cg("\nStarting roscore...\n")
os.system("roscore &")
time.sleep(3)
cg("\nShort wait before starting bag loop\n")
time.sleep(3)

timer = Timer(60*30)

while not timer.check():
	sys_str = "rosbag play "+bagpath+"/*.bag"
	cg(sys_str)
	os.system(sys_str)

cg("\nbagloop complete.\n")

#EOF
