#!/usr/bin/env python
from kzpy3.utils3 import *
exec(identify_file_str)
try:
    import pyperclip
    have_pyperclip = True
except:
    cr("cannot import pyperclip")
    have_pyperclip = False


cmd_to_show = ['python','nmc','bagloop','histdic']
#pro_to_show = ['kzpy3/Cars/n26Dec18/nodes/network_node.py']
if 'app' not in Arguments:
    Arguments['app'] = 'all'

for filt in ['ignore','require']:
    if filt not in Arguments:
        Arguments[filt] = []
    else:
        Arguments[filt] = Arguments[filt].split(',')

print_Arguments()

while True:
    #clear_screen()
    h=txt_file_to_list_of_strings(opjD('hist.txt'))
    #h=txt_file_to_list_of_strings(opjh('.bash_history'))
    H = {}
    for i in h:
        s = i.split(' ')
        #cm("'",s,"s")
        cmd = s[3]
        if cmd not in H:
            H[cmd] = {}
        if len(s) > 4:
            pro = s[4]
            if pro not in H[cmd]:
                H[cmd][pro] = []
            H[cmd][pro].append(' '.join(s[3:]))

    ks = sorted(H.keys())

    lst = []
    ctr = 0
    cy('0 quit')
    for k in ks:
        if k in cmd_to_show:
            #cw(k)
            es = sorted(H[k].keys())
            for e in es:
                try:
                    app = e.split('/')[1]
                except:
                    app = 'no app'
                if Arguments['app'] == 'all' or app == Arguments['app']:
                    l = H[k][e]
                    l = list(set(l))
                    for m in l:
                        #cr(m)
                        continue_ = False
                        for ig in Arguments['ignore']:
                            if ig in m:
                                continue_ = True
                                break
                        if continue_:
                            continue
                        continue_ = False
                        for ig in Arguments['require']:
                            if ig not in m:
                                continue_ = True
                                break
                        if continue_:
                            continue
                        lst.append(m)
                        if 'menu2' in m:
                            c_ = cy
                        elif 'Cars' in m:#is_even(ctr):
                            c_ = cg
                        elif 'Train' in m:
                            c_ = cb
                        else:
                            c_ = cm
                        if Arguments['app'] != 'all' or Arguments['app'] != 'no app':
                            n = m.replace(Arguments['app']+'/','')
                            n = n.replace('kzpy3/','')
                        c_(ctr+1,n)
                        ctr += 1
    try:
        a = input('-> ')
        assert type(a) == int
    except:
        continue
    if a == 0:
        break
    a -= 1
    #os.system(lst[a])
    if have_pyperclip:
        pyperclip.copy(lst[a])
        cy("In clipboard:","'"+lst[a]+"'")
    else:
        cr('cannot copy to clipboard becaue do not have pyperclip')
    answer = raw_input('run (y/[n])?')
    cm('***'+answer+'***')
    if answer == 'y':
        #os.system(lst[a])
        sys_str = d2n("gnome-terminal  --geometry 40x30+100+200 -x "+lst[a])
        os.system(sys_str)
#EOF